"""
CUSTOM CONSTANTS
"""
import os

DB_HOST = os.environ["MARIADB_HOST"]
DB_PORT = os.environ["MARIADB_PORT"]
DB_USER = os.environ["MARIADB_USER"]
DB_PASSWORD = os.environ["MARIADB_PASSWORD"]
DB_DATABASE = os.environ["MARIADB_DATABASE"]

RUNMODE = os.environ["RUNMODE"]

DID_HOST = os.environ["DID_HOST"]
DID_PORT = os.environ["DID_PORT"]

JWT_SECR = os.environ["JWT_SECR"]
JWT_EXPR = 7200 # JWT expires after 2 hours
JWT_ALGO = "HS256"

FE_HOST = os.environ["FE_HOST"]
CORS_ALLOWED_HOST = os.environ["CORS_ALLOWED_HOST"]
CORS_ALLOWED_LOCAL_PORT = os.environ["CORS_ALLOWED_LOCAL_PORT"]

"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$our&j-f@o1^^_yu#g21z2gg&)3tuj)_56fvq15+n-bg$#&d4)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = (RUNMODE == 'development')

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '192.168.35.10',
    FE_HOST,
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'app',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': DB_DATABASE,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'app.User'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS configuration
CORS_ORIGIN_WHITELIST = [
    'http://127.0.0.1:' + CORS_ALLOWED_LOCAL_PORT,
    'http://localhost:' + CORS_ALLOWED_LOCAL_PORT,
    CORS_ALLOWED_HOST,
]
CORS_ALLOW_CREDENTIALS = True
