version: '3.9'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.8.2-rc-focal
    volumes:
      - mrdata:/var/lib/mysql
    environment:
      - "MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}"
      - "MARIADB_USER=${MARIADB_USER}"
      - "MARIADB_PASSWORD=${MARIADB_PASSWORD}"
      - "MARIADB_DATABASE=${MARIADB_DATABASE}"
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin:5.1.3
    links:
      - "mariadb:db"
    container_name: phpmyadmin
    ports:
      - 60079:80
  did-core:
    image: haeramkeem/did-core
    container_name: did-core
    ports:
      - 7771:7771
    environment:
      - "INFURA_PID=${INFURA_PID}"
volumes:
  mrdata:
